// <auto-generated />
namespace TeduShopingOnline.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdateTable_Order_AddNewColumn_CustomerIdentityNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateTable_Order_AddNewColumn_CustomerIdentityNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201805280419257_UpdateTable_Order_AddNewColumn_CustomerIdentityNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
